# Generated by Django 4.2.1 on 2023-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_book_url_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="url_book",
        ),
        migrations.AddField(
            model_name="book",
            name="book_file",
            field=models.FileField(default="none", upload_to="pdfs"),
        ),
    ]
